### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by uetchy** [ClassicOldSong/create-initializer#2]
Hi, I've just stumbled upon your fork of [create-create-app](https://github.com/uetchy/create-create-app) and noticed that LICENSE in this repository is actually violating the MIT license, where you should have to keep the original license text as-is.

Please go through [this guide](https://gist.github.com/fbaierl/1d740a7925a6e0e608824eb27a429370) and update LICENSE on GitHub and npm, then you're good to go!

**Comment by ClassicOldSong** [comment]
Sorry for the late response! Now the license is fixed in 9c51f858e6af7f70f452732935fb2646df838528
